services:
  app:
    build: .
    container_name: transcript_formatter
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
    volumes:
      - .:app
      # this volume syncing allows you to change your code
      # where it will automattivally restart the docker container